export { default as marriage1 } from "./image1.jpg";
export { default as marriage2 } from "./image2.jpg";
// export { default as marriage3 } from "./image3.jpg";
export { default as marriage4 } from "./image4.jpg";
export { default as marriage5 } from "./image5.jpg";
export { default as marriage6 } from "./image6.jpg";
export { default as marriage7 } from "./image7.jpg";
export { default as marriage8 } from "./image8.jpg";
export { default as marriage9 } from "./image9.jpg";
export { default as marriage10 } from "./image10.jpg";
// export { default as marriage11 } from "./image11.jpg";
export { default as marriage12 } from "./image12.jpg";
export { default as marriage13 } from "./image13.jpg";
export { default as marriage14 } from "./image14.jpg";
export { default as marriage15 } from "./image15.jpg";
// export { default as marriage16 } from "./image16.jpg";
export { default as marriage17 } from "./image17.jpg";
export { default as marriage18 } from "./image18.jpg";
export { default as marriage19 } from "./image19.jpg";
export { default as marriage20 } from "./image20.jpg";
export { default as marriage21 } from "./image21.jpg";
export { default as marriage22 } from "./image22.jpg";
export { default as marriage23 } from "./image23.jpg";
export { default as marriage24 } from "./image24.jpg";
export { default as marriage25 } from "./image25.jpg";
export { default as marriage26 } from "./image26.jpg";
export { default as marriage27 } from "./image27.jpg";
export { default as marriage28 } from "./image28.jpg";
export { default as marriage29 } from "./image29.jpg";
export { default as marriage30 } from "./image30.jpg";
export { default as marriage31 } from "./image31.jpg";
export { default as marriage32 } from "./image32.jpg";
export { default as marriage33 } from "./image33.jpg";
export { default as marriage34 } from "./image34.jpg";
