export { default as bday1 } from "./image1.jpg";
export { default as bday2 } from "./image2.jpg";
export { default as bday3 } from "./image3.jpg";
export { default as bday4 } from "./image4.jpg";
export { default as bday5 } from "./image5.jpg";
// export { default as bday6 } from "./image6.jpg";
export { default as bday7 } from "./image7.jpg";
export { default as bday8 } from "./image8.jpg";
export { default as bday9 } from "./image9.jpeg";
export { default as bday10 } from "./image10.jpg";
export { default as bday11 } from "./image11.jpg";
export { default as bday12 } from "./image12.jpg";
export { default as bday13 } from "./image13.jpg";
